export const ActionTypes = {
    ADD_TO_CART : 'ADD_TO_CART',
    SET_PRODUCTS : 'SET_PRODUCTS',
    SIGNUP_USER : 'SIGNUP_USER',
    INCREMENT_CART_ITEM : 'INCREMENT_CART_ITEM',
    DECREMENT_CART_ITEM : 'DECREMENT_CART_ITEM',
    REMOVE_CART_ITEM : 'REMOVE_CART_ITEM',
    LOGIN_USER : 'LOGIN_USER',
    LOGOUT_USER : 'LOGOUT_USER',
    REMOVE_ERROR :  'REMOVE_ERROR'
};